name: continous-integration-ci

on: [push]

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v1
    
    - name: Setting up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    
    - name: Building the gradle
      working-directory: .
      run: |
        chmod +x gradlew
        ./gradlew build -x test

  test: 
    runs-on: macos-10.15
    needs: build

    steps:
      - uses: actions/checkout@v1
    
      - name: Setting up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Unit Testing
        working-directory: .
        run: |
          chmod +x gradlew
          ./gradlew build -x test